### ISSUE TITLE
Microsoft Edge Tools for VS Code - What is this error and how do I fix it?

### ISSUE THREAD

**Issue by mnosal** [microsoft/vscode-edge-devtools#1049]
I get an error when starting the project:

---------
Microsoft Edge Tools for VS Code, version: 2.0.0
--

Found hint at c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\index.js
c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 17:04:56] Connection to server got closed. Server will restart.
Found hint at c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\index.js
c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 17:05:00] Connection to server got closed. Server will restart.
Found hint at c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\index.js
c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 17:05:03] Connection to server got closed. Server will restart.
Found hint at c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\index.js
c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 17:05:07] Connection to server got closed. Server will restart.
Found hint at c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\index.js
c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\mn\Desktop\2022-05\project\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\mn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Error - 17:05:11] Connection to server got closed. Server will not be restarted.

**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
It seems to me there is a problem with your hint installation. @antross can you help?

**Comment by mnosal** [comment]
How can I help determine the cause of the problem?
Unfortunately I'm just learning about these tools so I don't know where or how to look for the cause.
[Google translate]

**Comment by antross** [comment]
@mnosal, this part of the log looks related and indicates we had trouble processing a particular file you had open:

> AnalyzerError: Unable to parse axe results null

The `axe` tool is what we use to help report accessibility errors in `.html`, `.jsx`, or `.tsx` files. If you are able to figure out which file caused the error and share it (or share a similar file which triggers the error) we should be able to investigate. I'd recommend closing all files, restarting Visual Studio Code, then re-opening files one at a time until the error occurs to narrow down which file is causing the error.

**Comment by mnosal** [comment]
The indicated problem always occurs when the project folder is started.

I test moved all the files of this project to a folder with a different name and the error disappeared. It looks as if VS Code has additional settings in the cache of that project.

Where to look for the settings from the project? How to clear them for a particular project?

**Comment by mnosal** [comment]
More information from:

The Microsoft Edge Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by codepo8** [comment]
This should be fixed by now, right?

**Comment by codepo8** [comment]
Duplicate, closed.
