### ISSUE TITLE
AnalyzerError: Unable to parse axe results null

### ISSUE THREAD

**Issue by angelania2020** [microsoft/vscode-edge-devtools#1105]
**Environment:**

OS (e.g., Windows 10): Windows 10 Pro
Extension version (e.g., 1.2.3): v2.1.0

**Describe the bug:**

I get two notifications when opening an html file in VS Code:

Microsoft Edge Tools server crashed 5 times in the last 3 minutes
A request has failed. See the output for more information. Source: Microsoft Edge Tools for VS Code (extension)

**It seems to me that the extension crashes when it scans the following lines of code which are used for embedding YouTube videos:**
**<iframe width="560" height="315" src="https://www.youtube.com/embed/PCHMZH998aY" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>**

**Expected behavior:**

Working extension

**Additional context:**

**Output:**

Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
^

AnalyzerError: Unable to parse axe results null
at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at runNextTicks (node:internal/process/task_queues:65:3)
at processImmediate (node:internal/timers:437:9)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
status: 'AnalyzeError'
}
[Info - 6:20:25 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
^

AnalyzerError: Unable to parse axe results null
at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at runNextTicks (node:internal/process/task_queues:65:3)
at processImmediate (node:internal/timers:437:9)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1519)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
status: 'AnalyzeError'
}
[Info - 6:20:30 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
^

AnalyzerError: Unable to parse axe results null
at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at runNextTicks (node:internal/process/task_queues:65:3)
at processImmediate (node:internal/timers:437:9)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
status: 'AnalyzeError'
}
[Info - 6:20:35 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
^

AnalyzerError: Unable to parse axe results null
at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at runNextTicks (node:internal/process/task_queues:65:3)
at processImmediate (node:internal/timers:437:9)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
status: 'AnalyzeError'
}
[Info - 6:20:40 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5454:19)
at Array.forEach ()
at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5449:22)
at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :5555:16)
at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6709:14)
at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6772:7)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6928:11)
at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6642:18)
at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6664:11)
at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules@hint\connector-local\dist\src\connector.js:244:38), :6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
^

AnalyzerError: Unable to parse axe results null
at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at runNextTicks (node:internal/process/task_queues:65:3)
at processImmediate (node:internal/timers:437:9)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
at async t.Analyzer.validateTextDocument (c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
at async c:\Users\Angelina.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
status: 'AnalyzeError'
}
[Error - 6:20:45 PM] Connection to server got closed. Server will not be restarted.

**Comment by captainbrosset** [comment]
Thanks a lot for the report. This is now on our list of bugs and we'll let you know when we have updates about a fix.
