### ISSUE TITLE
Which Edge version to download for debugging?

### ISSUE THREAD

**Issue by domderen** [microsoft/vscode-edge-devtools#135]
Hi,

I tried following the [CONTRIBUTING](https://github.com/microsoft/vscode-edge-devtools/blob/master/CONTRIBUTING.md) steps to initialize the codebase for debugging. I downloaded Edge browser from this link: [Microsoft Edge_84.0.505.0_Mac OS x64_chromium.tar](https://3rdpartycodeprod.blob.core.windows.net/download/Microsoft%20Edge%2F84.0.506.0%2FMac%20OS%20x64%2Fchromium.tar?sv=2019-02-02&st=2020-05-05T17%3A53%3A39Z&se=2020-05-05T19%3A33%3A39Z&sr=b&sp=r&sig=jDcooxNpiylyqAorubz%2FepJrygJLTc%2BbJYDmiuTd%2Fys%3D)

I created a `~/edge` directory, and copied files in the CONTRIBUTING docs, exported environment variables, and then ran:

```bash
npm install
npm run build
```

In the repository. `npm install` works fine, but `npm run build` is failing with:

```
 $ npm run build

> vscode-edge-devtools@1.0.7 build /Users/dominikderen/dev/vscode-edge-devtools
> npm run build-wp && npm run build-post


> vscode-edge-devtools@1.0.7 build-wp /Users/dominikderen/dev/vscode-edge-devtools
> webpack

Child host:
    Hash: 3e00429cf5f5c94e753f
    Version: webpack 4.36.1
    Time: 3561ms
    Built at: 2020-05-05 6:59:37 PM
                      Asset      Size     Chunks             Chunk Names
             host.bundle.js  16.9 KiB       host  [emitted]  host
         host.bundle.js.map  25.4 KiB       host  [emitted]  host
        messaging.bundle.js  5.61 KiB  messaging  [emitted]  messaging
    messaging.bundle.js.map   5.9 KiB  messaging  [emitted]  messaging
    Entrypoint host = host.bundle.js host.bundle.js.map
    Entrypoint messaging = messaging.bundle.js messaging.bundle.js.map
    [./src/common/webviewEvents.ts] 1.63 KiB {host} [built]
    [./src/host/host.ts] 2.15 KiB {host} [built]
    [./src/host/mainHost.ts] 234 bytes {host} [built]
    [./src/host/mainMessaging.ts] 252 bytes {messaging} [built]
    [./src/host/messaging.ts] 1.24 KiB {messaging} [built]
    [./src/host/toolsHost.ts] 3.89 KiB {host} [built]
    [./src/host/toolsResourceLoader.ts] 1.66 KiB {host} [built]
    [./src/host/toolsWebSocket.ts] 1.84 KiB {host} [built]

> vscode-edge-devtools@1.0.7 build-post /Users/dominikderen/dev/vscode-edge-devtools
> ts-node postBuildStep.ts

Patching files for release version
(node:71216) UnhandledPromiseRejectionWarning: Error: An expected file was not found: out/tools/front_end/main/MainImpl.js
    at patchFileForWebView (/Users/dominikderen/dev/vscode-edge-devtools/postBuildStep.ts:158:15)
(node:71216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Indeed I confirmed that the `MainImpl.js` file is not available in the above mentioned MS Edge (Chromium) package. There are just `main.js` & `main-legacy.js` files in that path. They look like post-build output files. 

I'm wondering if there is a different way MS Edge browser should be downloaded, so that it contains source devtools files?

Thanks in advance for your help!

**Comment by mliao95** [comment]
Hey Dominik!  Currently, the tools are set up to be compatible with the current version of Microsoft Edge stable (currently 81.0.416).  However, the tools should be able to support Edge versions up to 82.0.423.

**Comment by domderen** [comment]
Hey @mliao95 thanks for getting back to me! I downloaded Edge v81.0.416 and indeed it has the necessary files :) That helped with modifying the necessary files in the `postBuildStep.ts`. But now when I'm running `npm run build` on the current master branch, I get the following issues:

```
$ npm run build

> vscode-edge-devtools@1.0.8 build /Users/dominikderen/dev/vscode-edge-devtools
> npm run build-wp && npm run build-post


> vscode-edge-devtools@1.0.8 build-wp /Users/dominikderen/dev/vscode-edge-devtools
> webpack

Child host:
    Hash: b24334664009d6f47712
    Version: webpack 4.36.1
    Time: 3089ms
    Built at: 2020-05-09 11:40:29 AM
                      Asset      Size     Chunks             Chunk Names
             host.bundle.js  16.9 KiB       host  [emitted]  host
         host.bundle.js.map  25.4 KiB       host  [emitted]  host
        messaging.bundle.js  5.61 KiB  messaging  [emitted]  messaging
    messaging.bundle.js.map   5.9 KiB  messaging  [emitted]  messaging
    Entrypoint host = host.bundle.js host.bundle.js.map
    Entrypoint messaging = messaging.bundle.js messaging.bundle.js.map
    [./src/common/webviewEvents.ts] 1.63 KiB {host} [built]
    [./src/host/host.ts] 2.15 KiB {host} [built]
    [./src/host/mainHost.ts] 234 bytes {host} [built]
    [./src/host/mainMessaging.ts] 252 bytes {messaging} [built]
    [./src/host/messaging.ts] 1.24 KiB {messaging} [built]
    [./src/host/toolsHost.ts] 3.89 KiB {host} [built]
    [./src/host/toolsResourceLoader.ts] 1.66 KiB {host} [built]
    [./src/host/toolsWebSocket.ts] 1.84 KiB {host} [built]
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(10,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(10,34)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,1)
          TS1128: Declaration or statement expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,13)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,52)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts(8,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts(8,34)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts(8,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts(8,57)
          TS1005: ';' expected.
Child extension:
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(10,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(10,34)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,1)
          TS1128: Declaration or statement expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,13)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/index.d.ts(11,52)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts(8,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/diffLines.d.ts(8,34)
          TS1005: ';' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts(8,13)
          TS1005: '=' expected.
    
    ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts
    [tsl] ERROR in /Users/dominikderen/dev/vscode-edge-devtools/node_modules/jest-diff/build/printDiffs.d.ts(8,57)
          TS1005: ';' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-edge-devtools@1.0.8 build-wp: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-edge-devtools@1.0.8 build-wp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dominikderen/.npm/_logs/2020-05-09T09_40_31_349Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-edge-devtools@1.0.8 build: `npm run build-wp && npm run build-post`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-edge-devtools@1.0.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dominikderen/.npm/_logs/2020-05-09T09_40_31_401Z-debug.log
```

All the lines it is complaining about look like this:

```
export type { DiffOptions, DiffOptionsColor } from './types';
```

So I'm guessing my dev env setup doesn't like the `export type` syntax. Is it related to a new release of TypeScript? Is there a specific version of TypeScript I should have installed for this to work?

Thanks in advance for your help!

**Comment by domderen** [comment]
Hey, I updated TypeScript to version `3.8.3` and it fixed the above issue. I managed to get the `postBuildStep.ts` to execute correctly. I then moved to running the extension using the `Launch Extension` launch configuration. It runs, executes build steps correctly, but then when the new VS window is open, I get this error in the debug console:

```
Failed to execute fetch TypeError: Cannot read property '0' of undefined
	at getWorkspaceRootPath (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
	at fetch (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
	at fetchRemoteUrl (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
gitlab_service.js:120
Failed to execute fetch TypeError: Cannot read property '0' of undefined
	at getWorkspaceRootPath (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
	at fetch (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
	at fetchRemoteUrl (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
gitlab_service.js:108
Failed to execute fetch TypeError: Cannot read property '0' of undefined
	at getWorkspaceRootPath (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
	at fetch (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
	at fetchRemoteUrl (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
gitlab_service.js:120
Failed to execute fetch TypeError: Cannot read property '0' of undefined
	at getWorkspaceRootPath (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
	at fetch (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
	at fetchRemoteUrl (/Users/dominikderen/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
```

It looks like the `vscode.workspace.workspaceFolders` from the `vscode` package is set to `undefined`. It retries internally I think to download required files, but still fails on this command. 

I'm running on Mac 10.15.3 and vscode version: `1.44.2 ff915844119ce9485abfe8aa9076ec76b5300ddd x64`. Is this an issue specific to my dev env setup?

**Comment by codepo8** [comment]
Hey there Dominic, I will check if it works on my machine and we can go from there.

**Comment by domderen** [comment]
Thanks, that would be fantastic!

**Comment by codepo8** [comment]
OK, I went through the process and the main thing was to get the correct version of edge. 
I downloaded the following and that works with the described process. 

I also updated TypeScript to the latest, which was one error.

This is on MacOS Catalina. 10.15.4

![image](https://user-images.githubusercontent.com/13508/81824671-08679480-9536-11ea-896b-860717986eda.png)

**Comment by domderen** [comment]
Hey Christian,

Thanks for checking this! I updated my Mac to 10.15.4 & VSCode to 1.45.0 only to see that the error still shows up. But then I noticed that the error is happening in the `Gitlab Workflow` VSCode extension. I disabled the extension, and debugging started to work :)

I'm up and running now, thank you very much for your help!
