### ISSUE TITLE
Add 'testing' to list of Microsoft Edge Tools

### ISSUE THREAD

**Issue by theuntested** [microsoft/vscode-edge-devtools#1845]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

Add 'testing' to list of Microsoft Edge Tools using Microsoft Playwright Codegen. Example "Launch an instance of Microsoft Edge to begin inspecting, modifying or testing webpages."

**Comment by captainbrosset** [comment]
I'm not sure I understand what you're asking. Could you please provide more detailed information.

**Comment by theuntested** [comment]
Add 'testing' to list of VS Code Microsoft Edge Tools capabilities by using Microsoft Playwright Codegen, I'm reaching here.

Example, "Launch an instance of Microsoft Edge to begin inspecting, modifying or **testing** webpages."

![CaptureVSCodeEdgeToolsLaunch](https://github.com/microsoft/vscode-edge-devtools/assets/2695210/9af91467-789e-4f77-88e4-81f6383e1d3a)

**Comment by theuntested** [comment]
Is your feature request related to a problem? Please describe. I don't believe so, but I don't know.

Describe the solution you'd like: As a tester I'd like the ability to launch Edge and use the developer tools which could include Playwright. Currently, I see BlobNotFoundThe specified blob does not exist. RequestId:996062f0-a01e-004b-1e4e-1d29aa000000 Time:2023-11-22T14:14:43.0335168Z 
2023-11-22 10:09:30.832 [error] Error: WebSocket is not open: readyState 0 (CONNECTING)
    at N.send (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1321298)
    at ae.onOpen (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1666855)
    at N.socket.onopen (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1666769)
    at N.o (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1291636)
    at N.emit (node:events:513:28)
    at N.setSocket (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1319683)
    at ClientRequest.<anonymous> (c:\Users\jallen\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension.js:1:1325329)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnData (node:_http_client:582:11)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023-11-22 10:10:37.590 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
, but this maybe Zscaler at work. Sorry to be more confusing than ever.

Describe alternatives you've considered: Chrome Playwright extensions. VS Code Playwright extension.

Additional context: An Edge Playwright Extension usable by a VS Code Dev
![CaptureVSCodeEdgeToolsLaunch2](https://github.com/microsoft/vscode-edge-devtools/assets/2695210/72b4aa41-5fe7-4a7e-a588-7204678d82c0)
Tools launched browser.

Happy Thanksgiving

**Comment by captainbrosset** [comment]
Thanks for the details. Renaming the issue accordingly.

**Comment by theuntested** [comment]
> Thanks for the details. Renaming the issue accordingly.

This would be useful. Especially if Codegen, Copilot, Playwright and Lighthouse could somehow interact to create meta automation.
