### ISSUE TITLE
Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by darknoon** [microsoft/vscode-edge-devtools#2410]
**Environment (please complete the following information):**
 - macOS 14.6.1 (23G93)
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**
I just installed this extension for the first time and tried to run it. This is the error I encountered.

**Repro steps:**
Command Palette → "Microsoft Edge Tools: Open Browser"

> Command 'Microsoft Edge Tools: Open Browser with DevTools' resulted in an error
> Cannot read properties of undefined (reading 'fsPath')

<img width="281" alt="Screenshot 2024-09-09 at 12 36 18 PM" src="https://github.com/user-attachments/assets/9a735b9c-765a-4c8f-aec1-49a9cad29bb2">

**Expected behavior:**
Runs browser

**Additional context:**

**Comment by mistcat** [comment]
I too have this error

**Comment by btippett** [comment]
Same issue here. M1 Mac running Sequoia. All apps installed with Homebrew.

**VS Code**
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

**Microsoft Edge Tools for VS Code**
v2.1.6

**Microsoft Edge**
Version 129.0.2792.52 (Official build) (arm64)

**Extension Settings*
"vscode-edge-devtools.browserArgs": []
"vscode-edge-devtools.browserFlavor": "Default",
"vscode-edge-devtools.defaultEntrypoint": "index.html",
"vscode-edge-devtools.defaultUrl": "about:blank"
"vscode-edge-devtools.headless": true
"vscode-edge-devtools.hostname": "localhost"
"vscode-edge-devtools.pathMapping": {
   "/": "${workspaceFolder}"
 },
"vscode-edge-devtools.port": 9222,
"vscode-edge-devtools.showWorkers": false,
"vscode-edge-devtools.sourceMapPathOverrides": {
  "webpack:///./*": "${webRoot}/*",
  "webpack:///src/*": "${webRoot}/*",
  "webpack:///*": "*",
  "webpack:///./~/*": "${webRoot}/node_modules/*",
  "webpack://*": "${webRoot}/*",
  "meteor://💻app/*": "${webRoot}/*"
},
"vscode-edge-devtools.sourceMaps": true,
"vscode-edge-devtools.timeout": 10000,
"vscode-edge-devtools.useHttps": false,
"vscode-edge-devtools.userDataDir": true,
"vscode-edge-devtools.webhint": true,
"vscode-edge-devtools.webhintInstallNotification": true,
"vscode-edge-devtools.webRoot": "${workspaceFolder}"

**Comment by hannaofsweden** [comment]
Here is the error output. I'm also on Mac M1 and Sequoia.

2024-09-29 21:22:48.183 [error] TypeError: Cannot read properties of undefined (reading 'fsPath')
    at Qh (/Users/johannajohansson/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-2.1.6/out/extension.js:2:1509346)
    at /Users/johannajohansson/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-2.1.6/out/extension.js:2:1507207
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:161:210554)
    at h.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:161:211414)
    at y.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:5968)
    at y.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:5734)
    at y.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4767)
    at y.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:3602)
    at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:2297)
    at r.B (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
    at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:184:8635)
    at r.B (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
    at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:184:6761)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain.emit (node:domain:488:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) vscode-edge-devtools-view.launchHtml {"value":"ms-edgedevtools.vscode-edge-devtools","_lower":"ms-edgedevtools.vscode-edge-devtools"}

**Comment by diasm3** [comment]
same here please

**Comment by KevinRohn** [comment]
same here

**Comment by dlibis** [comment]
any updates on this bug?

**Comment by NishantDesai1306** [comment]
Any updates on this issue? is it looking for node at some specific location?

**Comment by tcmulder** [comment]
Getting this bug also when running `Command Palette → "Microsoft Edge Tools: Open Browser"`. However, if I click the Edge icon in my sidebar and the _Launch Instance_ button, the browser opens fine... weird.

**Comment by wheeleran** [comment]
i tried the 'launch instance' button and nothing happens for me.
