### ISSUE TITLE
Edge not launching

### ISSUE THREAD

**Issue by mrvkino** [microsoft/vscode-edge-devtools#464]
**Environment (please complete the following information):**
 - OS: Mac OS 11.5.2 (20G95)
 - Extension version: 1.2.1

**Describe the bug:**
When I launch an edge instance it des not always launch. I restart VSCode or edge and it does not launch. It seems I need to do a restart for it to work.

**Repro steps:**
- Launch vscode
- Setup the launch config with:
```json
"configurations": [
	{
		"name": "Launch Microsoft Edge and open the Edge DevTools",
		"request": "launch",
		"type": "vscode-edge-devtools.debug",
		"url": "http://127.0.0.1:5000/projects_list/1",
		"vscode-edge-devtools.browserFlavor": "Default",
	}
]
```
- Launch an instance with the extension button or the debug shortcut
- Nothing happens

**Expected behavior:**
An instance of edge should start with the dev tool attached in vscode

**Additional context:**
This is VSCode console log.
```log
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Failed to launch the browser process![0818/143029.251313:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee2565000, 0x2000): (os/kern) invalid address (1)[0818/143029.548512:WARNING:crash_report_exception_handler.cc(302)] UniversalExceptionRaise: (os/kern) failure (5)TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error: Failed to launch the browser process![0818/143029.251313:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee2565000, 0x2000): (os/kern) invalid address (1)[0818/143029.548512:WARNING:crash_report_exception_handler.cc(302)] UniversalExceptionRaise: (os/kern) failure (5)TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md	at onClose (/Users/mrogersvallee/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-1.2.1/out/extension.js:52351:20)	at ChildProcess.<anonymous> (/Users/mrogersvallee/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-1.2.1/out/extension.js:52342:79)	at ChildProcess.emit (events.js:327:22)	at ChildProcess.EventEmitter.emit (domain.js:467:12)	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]Failed to launch the browser process!
[0818/143029.251313:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee2565000, 0x2000): (os/kern) invalid address (1)
[0818/143029.548512:WARNING:crash_report_exception_handler.cc(302)] UniversalExceptionRaise: (os/kern) failure (5)


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error: Failed to launch the browser process!
[0818/143029.251313:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee2565000, 0x2000): (os/kern) invalid address (1)
[0818/143029.548512:WARNING:crash_report_exception_handler.cc(302)] UniversalExceptionRaise: (os/kern) failure (5)


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

	at onClose (vscode-file://vscode-app/Users/mrogersvallee/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-1.2.1/out/extension.js:52351)
	at ChildProcess.<anonymous> (vscode-file://vscode-app/Users/mrogersvallee/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-1.2.1/out/extension.js:52342)
	at ChildProcess.emit (events.js:327)
	at ChildProcess.EventEmitter.emit (domain.js:467)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

**Comment by bgoddar** [comment]
Thank you for reporting the issue. Sorry to hear that the browser is not launching correctly. This looks like a potential issue with our dependency on puppeteer. 2 questions that might help us narrow down the issue:
1. Do you know what version of Edge you are targeting with "Default" you can find out by navigating to edge://verison?
2. Are you using the "headless" setting from the extension?

**Comment by mrvkino** [comment]
No problem!

1. I am targeting the latest stable version of Edge
```
Microsoft Edge | 92.0.902.78 (Official build) (x86_64)
-- | --
Revision | cf138c12fbef5d68392247688f16ca31d2b55bc5
Operating system | macOS Version 11.5.2 (Build 20G95)
JavaScript | V8 9.2.230.29
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.78
Command-line | /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge --flag-switches-begin --flag-switches-end
Executable path | /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
Profile path | /Users/mrogersvallee/Library/Application Support/Microsoft Edge/Default
Variations | d1c8379-d8d26f5ef479687f-d8d26f5eb0dfe6da-d8d26f5eae973cba-d8d26f5ef183bcf3-d8d26f5e40d468f2-d8d26f5ede911d62-ca7d8d805748b3a8-ca7d8d8023f7e829-ca7d8d8065570806-ca7d8d806055c54b-ca7d8d8067eb7685-ca7d8d80b9dad4f7-ca7d8d80180a461-ca7d8d80ac1ea36f-ca7d8d80fe7944c-ca7d8d80b4466e25-ca7d8d8032bc5dae-ca7d8d805da7d746-ca7d8d8027d27de7-ca7d8d8068fd18d7-ca7d8d804ea303a6-ca7d8d80aa88e8d8-ca7d8d80c028a58a-ca7d8d803b4f6f6-ca7d8d8014b833ba-ca7d8d803ee6367e-ca7d8d804c556629-d8d26f5ec1aadbf9-d8d26f5e5d006089-d8d26f5ed3706a2c-d8d26f5ecafbaa05-d8d26f5e2607cc0a-d8d26f5e983a7de-d8d26f5e63f86d58-d8d26f5efbc3384b-d8d26f5e5a745ca7-d8d26f5eb1508168-d8d26f5e41ae839f-d8d26f5ed0fd96a-d8d26f5ee6e2bdd1-d8d26f5e231ef928-d8d26f5e29bf163-d8d26f5ef672b9be-d8d26f5ec2507b9-d8d26f5ed8db6806-d8d26f5eea20b422-d8d26f5e9539fc9e-d8d26f5ee522e843-d8d26f5e360dbb47-d8d26f5eb46e9d76-d8d26f5e96098e45-d8d26f5ee15deb37-d8d26f5edaf8ad14-d8d26f5ef94057ff-d8d26f5ef8645af2-d8d26f5ef959761-d8d26f5e4914d477-d8d26f5e819fc48c-d8d26f5e2eeca73a-d8d26f5ef08695c7-d8d26f5e37def2a8-d8d26f5ea1598a48-d8d26f5eaa74f0b0-d8d26f5e
```
2. No I am not. I tried it, and it works only in headless mode.

**Comment by bgoddar** [comment]
Thanks for the more detailed information! I'll see if I can figure out if there is anything on our side we can do to avoid these puppeteer errors. We also have work in progress to more gracefully report and handle different types of unexpected errors, and I'll make sure this case gets added to the list of places we are looking to address

**Comment by mrvkino** [comment]
Great! If you have any issue reproducing the error, I am willing to run some test on my side to help.

BTW, I tried with the latest version 1.3.0 and I have the same issue. Also, I forgot to mentioned, I had the same issue when It was the only extension enabled.

**Comment by mliao95** [comment]
Hey! I was trying to repro it on a Mac with the configuration given in your initial post. Unfortunately, I wasn't able to repro the issue. Do you happen to have a sample repo or updated repro steps I could try out? Thanks!

**Comment by mrvkino** [comment]
Hi, I booted my laptop to try to setup a playground for this issue. Now, everything works!?

So I am a bit confused why a reboot would change the behaviour. Unless it relies on some process from macOS and it crashed before the reboot.

Since it is a transient issue (software crashing randomly), it will be hard for me to give you a sample.

Might as well close it unless someone else report the same issue.

If I figure a way to give you a reproducible playground for this, I will reopen an issue.

Thanks

**Comment by bgoddar** [comment]
Thanks for taking the time to look into this and attempt to set up a repro. I'm glad things are working for you now after the reboot. Your theory on a crashed or hanging process makes sense to me, and I agree I don't think there is much we can do on this at the moment. But we will keep an eye out for this behavior as well and reopen if we get more info.
