### ISSUE TITLE
DevTools not opened

### ISSUE THREAD

**Issue by sarazmi02** [microsoft/vscode-edge-devtools#861]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

I opened the edge extension and there is a button (launch project) and no (lanch instance)

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment]
Was this a one-off or does this happen every time for you?

**Comment by guilhermetod** [comment]
Not working for me too. Neither `Launch Instance` or `Launch Project` seem do something. They rarely blink the debugging bar, but it almost instantly go away.

I searched the extension output and extracted this: 


```
Found hint at c:\Users\Omnier\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
(node:8716) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\Omnier\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:139525
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:8716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8716) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\Omnier\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:139525
(node:8716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:8716) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\Omnier\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:139525
(node:8716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:8716) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\Omnier\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\Omnier\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.3\node_modules\vscode-webhint\dist\src\server.js:1:139525
(node:8716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

I'm currently on Windows 11 build 22543, but running VSCode and the project in WSL.

**Comment by Outpox** [comment]
Same here `Launch Project` doesn't start Edge and when using the default config nothing happens.  
Using Windows 10 (version 20H2 build 19042.1466) and my files are in WSL2.

**Comment by leiyuxuan688** [comment]
Not working for me too... await

**Comment by codepo8** [comment]
Yes, we are aware of this and working on it.
