### ISSUE TITLE
Error: "Unable to start webhint."

### ISSUE THREAD

**Issue by hxlnt** [microsoft/vscode-edge-devtools#910]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 11
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**
<img width="336" alt="image" src="https://user-images.githubusercontent.com/9647195/156410142-1d15ca49-5846-4fab-8c9c-cd65e83127f4.png">

**Additional context:**
Snippet from output:
```
Found hint at c:\Users\raweil\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
(node:13460) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\raweil\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1505)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:13460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:13460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13460) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\raweil\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:139525
(node:13460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:13460) UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\raweil\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1204
    at async t.Analyzer.validateTextDocument (c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:1129)
    at async c:\Users\raweil\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.5\node_modules\vscode-webhint\dist\src\server.js:1:139525

```

**Comment by antross** [comment]
@hxlnt any chance you could share an example project where you hit this (or is this happening for you across different startup projects)?

I ask because this part of the output seems relevant:
`UnhandledPromiseRejectionWarning: AnalyzerError: Connector local only works with local files or directories`

The error suggests webhint thought some file path we passed in for analysis was a URL instead (which in theory shouldn't be happening in this extension).

**Comment by GunnerGuyven** [comment]
This happens for me in almost every project I open.  I suspect some common configuration file is triggering it.  Here is an example project that triggers this for me using `File: Open Folder...` and targeting the root of this repository:

https://github.com/GunnerGuyven/c_sample

VSCode was recently upgraded, and I noticed this start happening in the last week. Environment Details:

VSCode About
```
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
Extension
```
Name: Microsoft Edge Tools for VS Code
Id: ms-edgedevtools.vscode-edge-devtools
Description: Use the Microsoft Edge Tools from within VS Code to see your site's runtime HTML structure, alter its layout, fix styling issues as well as see your site's network requests.
Version: 1.4.5
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools
```

**Comment by GunnerGuyven** [comment]
After some fiddling, if I make sure that no files are auto loading in the project (weren't open from the last session) and no tools are loading files automatically (removed my `c_cpp_properties.json`) file, then this warning doesn't pop up.  Then when I select the `launch.json` file and open it for editing, this warning appears.

**Comment by GunnerGuyven** [comment]
Further testing, I can open every file in this project, and nothing causes the warning until I open either the `launch.json` or `task.json` files.  As a test I created `test.json` in the root.  This file is empty.  No warning occurs on initial load until I open this empty `json` file.

**Comment by antross** [comment]
Thanks @GunnerGuyven, that's very helpful!

I was able to repro the problem using a `json` file. It appears the extension is getting invoked when opening a json file to analyze a collection of vscode-internal files for some reason: 
* `vscode://schemas/vscode-extensions`
* `vscode://schemas/settings/configurationDefaults`
* `vscode://schemas/settings/resourceLanguage`
* ...

I'm not yet certain if this is intentional or not on VS Code's part (feels like a variation of https://github.com/microsoft/vscode-languageserver-node/issues/506), but we should be able to ignore such URLs easily enough at the extension level before passing them into webhint.

**Comment by jsma** [comment]
Is there a way to manually get webhint updated in VS Code or do we have to wait for an official Edge Tools extension release to 1.4.7? This extension has been broken for me since the VS Code March 2022 auto-update yesterday and is also broken in the Insider's Edition, I had not encountered this error previously.
