### ISSUE TITLE
webhint server crashes with "Unable to parse axe results null"

### ISSUE THREAD

**Issue by antross** [microsoft/vscode-edge-devtools#979]
Version: 1.67.0-insider (system setup)
Commit: a9288be67bab4e9c4dbe62207f01fafc2bdaadcb
Date: 2022-04-15T05:16:11.219Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22598

```
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Info  - 10:16:40 PM] Connection to server got closed. Server will restart.

```

_Originally posted by @OpenWaygate in https://github.com/microsoft/vscode-edge-devtools/issues/954#issuecomment-1100888449_

**Comment by Donald0101** [comment]
Please 🙏 help me on JavaScript Base on this subjects of debugging and
setting up the configuration on Json.

**Comment by antross** [comment]
@OpenWaygate I haven't been able to reproduce the issue yet on my machine (was trying with the 1.67.0 VS Code Insider's build in case that was related). Does this always happen for you or does it only occur when you have specific projects/files open?

**Comment by OpenWaygate** [comment]
I am confused that I cannot reproduce it too.

Now it seems that every time I open vs code, it will `Updating shared version of "hint"` and my Windows Terminal will pop up without any prompt but the title.

![image](https://user-images.githubusercontent.com/27287694/163845941-ad72dae2-7f55-42f9-817b-82b6457259cd.png)
```
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Updating shared version of "hint"
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '@hint/configuration-development@latest',
npm verb cli   'hint@latest',
npm verb cli   'typescript@latest',
npm verb cli   '--save-dev',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.5.3
npm info using node@v16.14.0
npm timing npm:load:whichnode Completed in 0ms
...
npm timing reify Completed in 1701ms

up to date, audited 592 packages in 2s

70 packages are looking for funding
  run `npm fund` for details

9 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm timing command:install Completed in 1714ms
npm verb exit 0
npm timing npm Completed in 2230ms
npm info ok 
```

**Comment by antross** [comment]
Thanks @OpenWaygate that does make me think this may have been related to a specific file being open. If you're able to hit this again let me know. 

As for the terminal instance popping up, that's being tracked by #976

**Comment by antross** [comment]
I'm going to go ahead and close this issue since neither of us can reproduce it anymore, but if you do manage to repro it again please feel free to re-activate. My guess is this may be specific to a particular piece of content being scanned so if we can narrow down what's triggering it we can figure out what's going on.

**Comment by angelania2020** [comment]
Environment:

OS (e.g., Windows 10): Windows 10 Pro
Extension version (e.g., 1.2.3):  v2.1.0

Describe the bug:

I get two notifications when opening an html file in VS Code:

Microsoft Edge Tools server crashed 5 times in the last 3 minutes
A request has failed. See the output for more information. Source: Microsoft Edge Tools for VS Code (extension)

**It seems to me that the extension crashes when it scans the following lines of code, which are used for embedding YouTube videos:
				<iframe width="560" height="315" src="https://www.youtube.com/embed/PCHMZH998aY"
					allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
					allowfullscreen></iframe>**

Expected behavior:

Working extension

Additional context:

Output:

Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 6:20:25 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 6:20:30 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 6:20:35 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Info  - 6:20:40 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\xampp\htdocs\portfolio"
Trying to load shared version
Found hint at c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
Running axe-core failed: allowedOrigins value "null" is not a valid origin
Error: allowedOrigins value "null" is not a valid origin
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5454:19)
    at Array.forEach (<anonymous>)
    at postMessage (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5449:22)
    at post (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:5555:16)
    at _respondable (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6709:14)
    at _sendCommandToFrame (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6772:7)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6928:11)
    at pop (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6642:18)
    at Object.defer (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6664:11)
    at eval (eval at evaluate (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\@hint\connector-local\dist\src\connector.js:244:38), <anonymous>:6912:11)
c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\Angelina\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\Angelina\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.0\node_modules\vscode-webhint\dist\src\server.js:1:139563 {
  status: 'AnalyzeError'
}
[Error - 6:20:45 PM] Connection to server got closed. Server will not be restarted.

**Comment by jmagaram** [comment]
I created the .hintrc file and now see this error in the output. But I was seeing this error even before I created the .hintrc file. I created a brand new React project using `npm create vite@latest` from `https://vite.dev/guide/` and see this error from the Edge Dev Tools. I doubt there is something weird about my configuration on my computer.

```
Node.js v20.18.1
[Error - 10:27:32 AM] Server process exited with code 1.
[Info  - 10:27:32 AM] Connection to server got closed. Server will restart.
true
Error loading "hint" package from "/Users/justinmagaram/Source/hot"
Trying to load shared version
Found hint at /Users/justinmagaram/Library/Application Support/Code/User/globalStorage/ms-edgedevtools.vscode-edge-devtools/node_modules/hint/dist/src/lib/index.js
```
